#!/bin/bash

# This script creates the 300 band LW spectral file sp_lw_300_jm3
# using the same data as the GA9 broadband file.
# GA9 bands  ->  300 bands:
#         1  ->    1 -  40
#         2  ->   41 -  55
#         3  ->   56 -  59 +  76 -  80
#         4  ->   60 -  75
#         5  ->   81 -  99 + 113 - 120
#         6  ->  100 - 112
#         7  ->  121 - 133
#         8  ->  134 - 150
#         9  ->  151 - 300

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

cp $RAD_DATA/spectra/ga7_ref/sp_lw_300_jm2 .
cp $RAD_DATA/spectra/ga7_ref/sp_lw_300_jm2_k .
specfile="sp_lw_300_jm2"


# Aerosols
rm -f *.avg
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a soluble_300.avg $RAD_DATA/aerosol/soluble.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dustlike_300.avg $RAD_DATA/aerosol/dustlike.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a oceanic_300.avg $RAD_DATA/aerosol/oceanic.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a soot_300.avg $RAD_DATA/aerosol/soot.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a sulphuric_300.avg $RAD_DATA/aerosol/sulphuric.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a accumsulp_300.avg $RAD_DATA/aerosol/accumsulp.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a aitkensulp_300.avg $RAD_DATA/aerosol/aitkensulp.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a freshsoot_bond_300.avg $RAD_DATA/aerosol/freshsoot_bond.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a agedsoot_bond_300.avg $RAD_DATA/aerosol/agedsoot_bond.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a seasaltfilm_300.avg $RAD_DATA/aerosol/seasaltfilm.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a seasaltjet_300.avg $RAD_DATA/aerosol/seasaltjet.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div1_300.avg $RAD_DATA/aerosol/dust_div1.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div2_300.avg $RAD_DATA/aerosol/dust_div2.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div3_300.avg $RAD_DATA/aerosol/dust_div3.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div4_300.avg $RAD_DATA/aerosol/dust_div4.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div5_300.avg $RAD_DATA/aerosol/dust_div5.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div6_300.avg $RAD_DATA/aerosol/dust_div6.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a freshbiomass_bond_300.avg $RAD_DATA/aerosol/freshbiomass_bond.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a agedbiomass_bond_300.avg $RAD_DATA/aerosol/agedbiomass_bond.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a biogenic_300.avg $RAD_DATA/aerosol/biogenic.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a freshocff_300.avg $RAD_DATA/aerosol/freshocff.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a agedocff_300.avg $RAD_DATA/aerosol/agedocff.mon
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a nitrate_300.avg $RAD_DATA/aerosol/nitrate.mon
Cscatter_average -s $specfile -P 1 -w -p 290 \
  -a twobindust_1_300.avg $RAD_DATA/aerosol/twobindust_1.mon
Cscatter_average -s $specfile -P 1 -w -p 290 \
  -a twobindust_2_300.avg $RAD_DATA/aerosol/twobindust_2.mon


# Cloud
rm -f fit_lw_drop5_300 mon_lw_drop5_300
Cscatter_average -s $specfile -P 1 -t -p 250 \
  -f 5 fit_lw_drop5_300 mon_lw_drop5_300 1.e3 \
  $RAD_DATA/cloud/scatter_drop_type5


# Construct spectral file
mv sp_lw_300_jm3 sp_lw_300_jm3_old 2> /dev/null
mv sp_lw_300_jm3_k sp_lw_300_jm3_old_k 2> /dev/null
prep_spec << EOF
sp_lw_300_jm2
n
sp_lw_300_jm3
10
5
y
fit_lw_drop5_300
1.50000E-06 5.00000E-05
11
soluble_300.avg
y
11
dustlike_300.avg
y
11
oceanic_300.avg
y
11
soot_300.avg
y
11
sulphuric_300.avg
y
11
accumsulp_300.avg
y
11
aitkensulp_300.avg
y
11
freshsoot_bond_300.avg
y
11
agedsoot_bond_300.avg
y
11
seasaltfilm_300.avg
y
11
seasaltjet_300.avg
y
11
dust_div1_300.avg
y
11
dust_div2_300.avg
y
11
dust_div3_300.avg
y
11
dust_div4_300.avg
y
11
dust_div5_300.avg
y
11
dust_div6_300.avg
y
11
freshbiomass_bond_300.avg
y
11
agedbiomass_bond_300.avg
y
11
biogenic_300.avg
y
11
freshocff_300.avg
y
11
agedocff_300.avg
y
11
nitrate_300.avg
y
11
twobindust_1_300.avg
y
11
twobindust_2_300.avg
y
-1
EOF

rm *.avg
rm sp_lw_300_jm2
rm sp_lw_300_jm2_k
rm -f fit_lw_drop5_300 mon_lw_drop5_300

exit 0
